# Generated by Django 5.0.2 on 2024-06-13 15:48

from django.db import migrations, models

from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(max_length=1000),
        ),
    ]
