# Generated by Django 5.0.2 on 2024-08-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_parent_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_sku',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
