# Generated by Django 5.0.2 on 2024-05-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skills_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(default='IN', max_length=100),
        ),
    ]
