# Generated by Django 5.0.2 on 2024-05-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_products_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
