# Generated by Django 5.0.2 on 2024-05-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sudent2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
