# Generated by Django 5.0.2 on 2024-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_student_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudent2',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sudent2',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
