# Generated by Django 5.0.6 on 2024-06-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_mymodel_mymodel_age_gte_18'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='MyModel',
        # ),
        # migrations.AddField(
        #     model_name='book',
        #     name='price',
        #     field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='book',
        #     name='published_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='products',
        #     name='slug',
        #     field=models.SlugField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='book',
        #     name='author',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.author'),
        # ),
        # migrations.AlterModelTable(
        #     name='book',
        #     table='book',
        # ),
    ]
