# Generated by Django 5.0.6 on 2024-06-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_mymodel_book_price_book_published_date_and_more'),
        ('home', '0013_products_slug'),
    ]

    operations = [
    ]
