# Generated by Django 5.0.6 on 2024-06-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20240608_2016'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='MyModel',
        # ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
