# Generated by Django 5.0.6 on 2024-06-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_mymodel_alter_book_table'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='MyModel',
        # ),
    ]
