# Generated by Django 5.0.6 on 2024-06-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_mymodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
