# Generated by Django 5.0.6 on 2024-06-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('price',)},
        ),
    ]
