# Generated by Django 5.0.6 on 2024-06-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-price',)},
        ),
    ]
