# Generated by Django 5.0.6 on 2024-06-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_brand_unique_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='brand',
            index_together={('brand_name', 'country')},
        ),
    ]
