# Generated by Django 5.0.2 on 2024-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_sudent2_age_gte_18'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'constraints': [models.CheckConstraint(check=models.Q(('age__gte', 25)), name='age_gte_25')],
                'indexes': [],
            },
            bases=('home.sudent2',),
        ),
        migrations.AddField(
            model_name='skills',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
