# Generated by Django 5.1.4 on 2025-01-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
