# Generated by Django 5.1.4 on 2025-01-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_booking_ticket_type_remove_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_person',
            field=models.IntegerField(default=1),
        ),
    ]
