# Generated by Django 5.1.3 on 2025-01-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_department_skill_rename_first_name_student_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='SkillName',
        ),
    ]
