# Generated by Django 5.0.2 on 2024-06-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('description',)},
        ),
    ]
