# Generated by Django 5.0.2 on 2024-06-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='thumbnail_mini',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
    ]
