# Generated by Django 5.1.6 on 2025-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobdescription_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='project_category',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
