# Generated by Django 5.1.4 on 2024-12-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='home_studen_name_48380a_idx'),
        ),
    ]
