# Generated by Django 5.1.4 on 2024-12-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_book_options_alter_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'default_related_name': 'book_model'},
        ),
    ]
