# Generated by Django 5.1.4 on 2024-12-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
