# Generated by Django 5.1.4 on 2024-12-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'default_related_name': 'author_books'},
        ),
    ]
